[project]
name = "hackiiit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "moya-ai",
]

[tool.uv.sources]
moya-ai = { git = "https://github.com/vishesh312/moya" }
